# Copyright (c) 2025 jacquarde


name: "Run Gradle task"

#permissions:
#    contents: read

inputs:
    tasks:
        description: "Tasks to be run by Gradle"
        required:    true
    disable-build-cache:
        description: "Use build cache"
        required:    false
        default:     ''
    disable-daemon:
        description: "Run with daemon"
        required:    false
        default:     ''

outputs:
    project-group:
        description: "Group of the project"
        value:       ${{steps.properties.outputs.group}}
    project-name:
        description: "Name of the project"
        value:       ${{steps.properties.outputs.name}}
    project-version:
        description: "Version of the project"
        value:       ${{steps.properties.outputs.version}}


runs:
    using: "composite"
    steps:

#    -   name:  "Fetch source"
#        shell: pwsh
#        run:   gh repo clone ${{github.repository}} . -- --branch ${{github.ref_name}} --depth 1
#        env:
#            GH_TOKEN: ${{github.token}}

    -   name: "Fetch source"
        uses: actions/checkout@v4

    -   name:  "Create wrapper"
        shell: pwsh
        env:
            GRADLE_ACTIONS_SKIP_BUILD_RESULT_CAPTURE: true
        run:   gradle wrapper --no-scan

    -   name: "Validate wrapper"
        uses: gradle/actions/wrapper-validation@v4

    -   name:  "Extract properties"
        id:    properties
        shell: pwsh
        env:
            GRADLE_ACTIONS_SKIP_BUILD_RESULT_CAPTURE: true
        run:   |
               Invoke-Expression -Command ".\gradlew properties -q --console=plain" `
                      | Select-String -Pattern '^(.+?) ?: ?(.*)$' `
                      | ForEach-Object -Process {
                   "$( $_.Matches.Groups[1] )=$( $_.Matches.Groups[2] )" >> $env:GITHUB_OUTPUT
               }

    -   name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
            add-job-summary-as-pr-comment:        on-failure
            build-scan-publish:                   true
            build-scan-terms-of-use-agree:        "yes"
            build-scan-terms-of-use-url:          "https://gradle.com/terms-of-service"
            cache-disabled:                       true
            dependency-graph-continue-on-failure: false
            dependency-graph:                     generate-and-submit
            develocity-injection-enabled:         true
            develocity-plugin-version:            3.19.2
            develocity-url:                       "https://scans.gradle.com"
            validate-wrappers:                    false

    -   name:  "Build with Gradle wrapper"
        shell: pwsh
        env:
            JACQUARDE_DISABLE_BUILD_CACHE: ${{inputs.disable-build-cache && '--no-build-cache' || ''}}
            JACQUARDE_DISABLE_DAEMON:      ${{inputs.disable-daemon && '--no-daemon' || '' }}
        run:   |
               ./gradlew ${{inputs.tasks}} ${env:JACQUARDE_DISABLE_BUILD_CACHE} ${env:JACQUARDE_DISABLE_DAEMON}

    -   name: "Upload build reports"
        uses: actions/upload-artifact@v4
        if:   always()
        with:
            name:              build-reports
            if-no-files-found: warn
            path:              '**/build/reports/'
